config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  resources :artworks do
    resources :bookings
  end

  resources :bookings do
    member do
      patch '/accepted', to: 'bookings#accepted'
      patch '/rejected', to: 'bookings#rejected'
      patch '/cancelled', to: 'bookings#cancelled'
    end
  end

  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  include PgSearch::Model

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :title, :price_per_day, presence: true
  multisearchable against: [:title, :description]

  pg_search_scope :search_by_title_and_description,
    against: [:title, :description],
    associated_against: {
      user: [:username]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :artwork
  belongs_to :user

  validates :start_date, :end_date, :price, :status, presence: true

  before_validation :set_price

  def set_price
    self.price = artwork.price_per_day * (end_date - start_date)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :artworks
  has_many :bookings
  has_many :booked_artworks, through: :bookings, source: :artwork

  validates :username, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
    if params[:search]
      @artworks = Artwork.all
      @artworks = Artwork.search_by_title_and_description(search_params[:query]) unless search_params[:query].empty?
      @artworks.includes(:bookings).where('bookings.start_date < ? AND bookings.end_date > ?',
                                           search_params[:end_date],
                                           search_params[:start_date])

    else
      @artworks = Artwork.all
    end
  end

  def show
    @artwork = Artwork.find(params[:id])
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.user = current_user
    if @artwork.save
      redirect_to dashboard_path(@user)
    else
      render :new
    end
  end

  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to dashboard_path
  end

  private

  def search_params
    params.require(:search).permit(:query, :start_date, :end_date)
    end

  def artwork_params
    params.require(:artwork).permit(:username, :title, :price_per_day, :description, :photo, :category)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @artwork = Artwork.find(params[:artwork_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @artwork = Artwork.find(params[:artwork_id])
    @booking.artwork = @artwork
    @booking.user = current_user
    @booking.status = "En attente"
    @booking.total_price = booking_price(@booking)

    if @booking.save!
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def accepted
    @booking = Booking.find(params[:id])
    @booking.status = "Approuvé"
   if @booking.save
     flash[:success] = "Vous avez accepté cette réservation !"
   end
   redirect_to dashboard_path
  end

  def rejected
    @booking = Booking.find(params[:id])
    @booking.status = "Refusé"
    if @booking.save
      flash[:success] = "Vous avez refusé cette réservation."
    end
    redirect_to dashboard_path
  end

  def cancelled
    @booking = Booking.find(params[:id])
    @booking.status = "Annulé"
    if @booking.save
      flash[:success] = "Vous avez annulé cette réservation."
    end
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end

  def booking_price(booking)
    ((booking.end_date.to_date - booking.start_date.to_date).to_i) * booking.artwork.price_per_day
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @users = User.joins(:artworks).group("users.id").having("count(artworks.id)>0").last(2)
  end

  def dashboard
    @user = current_user
    @bookings = @user.bookings
    @artworks = @user.artworks

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/index.html.erb
<h1 class="text-center m-5"> Oeuvres disponibles (<%= @artworks.size %>)</h1>

  <p class='anchor text-center mt-5'>
  <strong>
    <%= link_to "Abstrait", artworks_path(anchor: "artwork-#{Artwork.where(category: 'Abstrait').first.id}"), class: "anchor text-decoration-none mx-5" %>
    <%= link_to "Photos", artworks_path(anchor: "artwork-#{Artwork.where(category: 'Photos').first.id}"), class: "anchor text-decoration-none mx-5" %>
    <%= link_to "Street Art", artworks_path(anchor: "artwork-#{Artwork.where(category: 'Street Art').first.id}"), class: "anchor text-decoration-none mx-5" %>
    <%= link_to "Peinture", artworks_path(anchor: "artwork-#{Artwork.where(category: 'Peinture').first.id}"), class: "anchor text-decoration-none mx-5" %>
    <hr>
  </strong>
  </p>

<div class="cards-container">
  <% @artworks.each do |artwork| %>
    <div class="artwork-card">
      <%= link_to artwork_path(artwork) do %>

        <div class="artwork-photo-category">
          <%= cl_image_tag artwork.photo.key, height: 300, width: 400, crop: :fill %>
          <span id="artwork-<%= artwork.id %>"> <%= artwork.category %> </span>
        </div>

        <ul style="list-style: none;padding: 15px;margin: 20px 0;">
          <li class="mb-2"><strong><%= artwork.title %></strong></li>
          <li class="mb-1"><%= artwork.price_per_day %>€ par jour</li>
          <li>
            <%= link_to "Découvrir cette oeuvre", artwork_path(artwork), class: "btn btn-ghost" %>
          </li>
        </ul>
      <% end %>
    </div>
  <% end %>
</div>

app/views/artworks/new.html.erb
<div class="container">
  <div class="big-card p-5">
    <%= simple_form_for @artwork  do |f| %>
      <%#= f.input :username %>
      <%= f.input :title, label: "Titre de l'oeuvre" %>
      <%= f.input :price_per_day, label: "Prix par jour" %>
      <%= f.input :description, label: "Description" %>
      <%= f.input :category, label: "Catégorie", as: :select, collection: ['Peinture', 'Abstrait', 'Street Art', 'Photos'] %>
      <%= f.input :photo, label: "Photo" %>
      <%= f.submit "Créer une nouvelle oeuvre", class: "btn-formulaire mt-2" %>
    <% end %>
  </div>
</div>

app/views/artworks/show.html.erb
<div class="container ">
  <div class="big-card d-flex justify-content-between align-items-center">
    <div class="">
      <%= cl_image_tag @artwork.photo.key %>
    </div>
    <div class="p-5" style="position: relative;">
      <%=link_to artworks_path, class: "grey-arrow d-flex align-items-center" do%>
        <i class="fa-solid fa-arrow-left"></i>
        <p class="mb-0 ms-2">Retour aux oeuvres</p>
      <%end%>
      <h1><strong><%= @artwork.title %></strong></h1>
      <h2><strong><%= @artwork.username %></strong></h2>
      <p><strong><%=@artwork.price_per_day%>€</strong> / jour</p>
      <p><%= @artwork.description %></p>

      <div data-controller="reveal">
        <div class="d-flex mt-4 mb-4 justify-content-center">
          <%= button_tag "Consulter les disponibilités", class: "btn-ghost-show", data: { action: 'click->reveal#show' } %>
        </div>

        <div data-reveal-target="form" class="d-none">
          <%= simple_form_for [ @artwork, Booking.new ] do |f| %>
            <%= f.input :start_date, label: "Date de début" %>
            <%= f.input :end_date, label: "Date de fin" %>
          <div class= "d-flex mt-3 justify-content-center" >
            <%= f.submit "Réserver cette oeuvre", class: "btn-yellow-rounded mt-5"%>
          <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>


<%# <h1><strong>L'art chez vous</strong></h1>
      <p>Louez des oeuvres d'art pour un jour, un mois, un an. Selon vos envies.</p>
      <div class="input-group py-3 d-flex">
        <input type="text" class="btn-ghost form-control" placeholder="Un artiste, un style ou un mot-clé" aria-label="Recipient's username" aria-describedby="basic-addon2">
        <button class="btn-ghost" type="button">Début</button>
        <button class="btn-ghost" type="button">Fin</button> %>

<%# <div class="container">
  <div class="d-flex justify-content-between">
    <div class="col-6 artwork-info">
      <%= cl_image_tag @artwork.photo.key%>
    <%# </div>
    <div class="col-6 artwork-info">
      <h1><%= @artwork.title %>
      <%# <p><%= @artwork.description</p> %>
      <%# <h2><%= @artwork.price_per_day</h2> %>
      <%# <%= link_to "Réserver cette oeuvre", new_artwork_booking_path(@artwork), class: "btn btn-ghost" %>
    <%# </div> %>
  <%# </div> %>
<%# </div> %>

app/views/bookings/new.html.erb
<h1>Book a new artwork</h1>

<h2><%= @artwork.title %>, <%= @artwork.price_per_day%></h2>
<p><%= cl_image_tag @artwork.photo.key%></p>

<%= simple_form_for [ @artwork, @booking ] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit "Reserve this artwork", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/e5c8fb4766.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <div class="wrapping-container">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="big-card d-flex justify-content-between position-relative">
    <div class='p-5'>
      <div class=" d-flex flex-row">
        <img id="avatar-profil" class="avatar dropdown-toggle position-absolute" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars.githubusercontent.com/u/93728030?v=4"/>
      </div>
      <h1>Mes réservations</h1>
      <% if @bookings.length == 0 %>
        <p>'Vous n'avez pas de réservation en cours !'</p>
      <% else %>
        <% @bookings.each do |booking| %>
          <div class="card-product my-3">
            <%= cl_image_tag booking.artwork.photo.key %>
            <div class="card-product-infos">
              <h5><strong><%= link_to booking.artwork.title, artwork_path(booking.artwork) %></strong></h5>
              <p><strong><%= link_to booking.artwork.title, artwork_path(booking.artwork) %></strong> - du <%= booking.start_date %> au <%= booking.end_date %></p>
              <p><%= booking.total_price %>€</p>
              <p><%= link_to "Annuler", booking_path(booking), method: :delete, data: { confirm: "Etes-vous sûr.e?" }, class: 'btn-ghost-dashboard' %></strong></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class='p-5'>
      <h1>Mes oeuvres</h1>

      <% if @user.artworks.length == 0 %>
        <p>'Vous n'avez pas d'oeuvres à louer pour le moment !'</p>
      <% else %>
        <%# <% @user.artworks.each do |artwork| %>
          <%# <div class="card-product my-3"> %>
            <%# <%= cl_image_tag artwork.photo.key %>
            <%# <div class="card-product-infos"> %>
              <%# <h5><strong><%= link_to artwork.title, artwork_path(artwork)</strong></h5>  %>
              <%# <strong><p><%= link_to artwork.description, artwork_path(artwork)</strong></p>  %>
              <%# <p> <%= link_to "Accepter", accepted_booking_path() </p> %>
              <%# <p><%= link_to "Supprimer ", artwork_path(artwork), method: :delete, data: { confirm: "Are you sure?" } %></strong></p>
            <%# </div> %>
          <%# </div> %>
        <% @artworks.each do |artwork| %>
          <% artwork.bookings.where(status: "En attente").each do |booking| %>
            <div class="card-product my-3">
              <%= cl_image_tag booking.artwork.photo.key %>
              <div class="card-product-infos">
                <h5><strong><%= link_to booking.artwork.title, artwork_path(booking.artwork) %></strong></h5>
                <p class="mb-3"><strong><%= link_to booking.artwork.title, artwork_path(booking.artwork) %></strong> - du <%= booking.start_date %> au <%= booking.end_date %></p>
                <%= link_to "Accepter", accepted_booking_path(booking), method: :patch, data: { confirm: "Etes-vous sûr.e?" }, class: 'btn-ghost-dashboard' %></strong>
                <%= link_to "Refuser", rejected_booking_path(booking), method: :patch, data: { confirm: "Etes-vous sûr.e?" }, class: 'btn-ghost-dashboard' %></strong>
              </div>
            </div>
          <% end %>
        <% end %>
        <% @artworks.each do |artwork| %>
          <% artwork.bookings.where(status: "Approuvé").each do |booking| %>
            <div class="card-product my-3">
              <%= cl_image_tag booking.artwork.photo.key %>
              <div class="card-product-infos">
                <h5><strong><%= link_to booking.artwork.title, artwork_path(booking.artwork) %></strong></h5>
                <p><strong><%= link_to booking.artwork.title, artwork_path(booking.artwork) %></strong> - du <%= booking.start_date %> au <%= booking.end_date %></p>
                <p><strong><%= booking.status %></strong></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="big-card d-flex justify-content-between align-items-center">
    <div class="p-5">
      <h1 class="title mb-4"><strong>L'art chez vous</strong></h1>
      <h6>Louez des oeuvres d'art pour un jour, un mois, un an.</h6>
      <h6>Selon vos envies.</h6>
      <div class="py-3">
        <%= simple_form_for :search, url: artworks_path, method: :get, html: {class: 'form-inline' } do |f|  %>
          <div class="d-flex justify-content-between align-items-end mt-3">
            <div class="w-100">
              <%= f.input :query, label: false, placeholder: 'Recherchez un style, un artiste...', class: "form-control" %>
            </div>
             <%= f.submit 'Rechercher', class: "btn btn-outline-secondary mb-3 ms-2" %>
          </div>
        <% end %>
        <%# <% <input type="text" class="btn-ghost form-control" placeholder="Un artiste, un style ou un mot-clé" aria-label="Recipient's username" aria-describedby="basic-addon2">
        <button class="btn-ghost" type="button">Début</button>
        <button class="btn-ghost" type="button">Fin</button> %>
      </div>
      <div class="input-group-append d-flex justify-content-center mt-3">
      <%=link_to artworks_path do%>
       <button class="btn-yellow-rounded" type="button">Toutes nos oeuvres</button>
       <%end%>
      </div>
    </div>
    <div>
      <img src="https://images.unsplash.com/photo-1505909182942-e2f09aee3e89?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1772&q=80" alt="photo">
    </div>
  </div>
</div>

<div class="container mt-5">
  <h1 class="mb-5">Nos styles</h1>

  <div class="card-grid">
    <%= link_to artworks_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://render.fineartamerica.com/images/images-profile-flow/400/images-medium-large-5/w-i-l-l-p-o-w-e-r-vlad-bubnov.jpg)">
        Photos
      </div>
    <% end %>
    <%= link_to artworks_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.artmajeur.com/medias/standard/j/y/jyrendo/artwork/11637314_streetart-vs-figurativeart-80x60-cm.jpg)">
        StreetArt
      </div>
    <% end %>
    <%= link_to artworks_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://cdn.carredartistes.com/products_images/prod_20664/d_figuratif-100-x-100-cm-eric-munsch-sublime-orange-front-0.jpg)">
        Peintures
      </div>
    <% end %>
    <%= link_to artworks_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.artmajeur.com/medias/standard/o/l/olidumont/artwork/7904269_le-retour-aux-sources.jpg)">
        Abstrait
      </div>
    <% end %>
  </div>
</div>

<div class="container mt-5">
    <h1 class="mb-5">Top artistes de la semaine</h1>
    <div class="card-grid-artiste">
      <div class="card-category-artiste" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://assets.catawiki.nl/assets/2020/4/27/1/9/e/19eaaa07-5b10-43fa-93be-90778bbd1eb3.jpg)">
      <span data-bs-toggle="modal" data-bs-target="#exampleModal" style="cursor:pointer;">Alexander Calder</span>
      </div>
      <div class="card-category-artiste" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://sothebys-com.brightspotcdn.com/e2/64/1a594a2b46939614e83b8ee5e79f/marlene-dumas-artist-portrait.jpg)">Marlène Dumas
      </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <div class="modal-body">
        <h1>Alexander Calder</h1>
        <h6 class="mb-3">Peintre</h6>
        <p style="text-align: justify;">Peintre américain, né le 22 juillet 1898 à Lawnton et mort le 11 novembre 1976 à New York. Il est surtout connu pour ses mobiles ainsi nommés sur proposition de Marcel Duchamp lors de leur exposition à Paris en 1932 à la galerie Vignon, ses assemblages de formes animées par les mouvements de l'air, puis ses stabiles.</p>
        <div class="d-flex justify-content-between align-items-center">
          <img class="rounded" style="max-width: 130px; height: 200px; object-fit: cover;" src="https://images.unsplash.com/photo-1559102877-4a2cc0e37fce?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDd8fGFydHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60" alt="">
          <img class="rounded" style="max-width: 130px; height: 200px; object-fit: cover;" src="https://images.unsplash.com/photo-1571115764595-644a1f56a55c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjd8fGFydHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60" alt="">
          <img class="rounded" style="max-width: 130px; height: 200px; object-fit: cover;" src="https://images.unsplash.com/photo-1602188324312-e1cd6383d2fe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzR8fGFydHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60" alt="">
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer-clean mt-5 position-sticky-bottom ">
  <footer>
      <div class="container">
          <div class="row justify-content-center">
              <div class="col-sm-4 col-md-3 item">
                  <h3>Services</h3>
                  <ul>
                      <li><a href="#">Web design</a></li>
                      <li><a href="#">Development</a></li>
                      <li><a href="#">Hosting</a></li>
                  </ul>
              </div>
              <div class="col-sm-4 col-md-3 item">
                  <h3>About</h3>
                  <ul>
                      <li><a href="#">Company</a></li>
                      <li><a href="#">Team</a></li>
                      <li><a href="#">Legacy</a></li>
                  </ul>
              </div>

              <div class="col-lg-3 item social">
                <a href="facebook"><i class="fab fa-facebook"></i></a>
                <a href="instagram"><i class="fab fa-instagram"></i></a>
                <a href="twitter"><i class="fab fa-twitter"></i></a>
                <a href="github"><i class="fab fa-github"></i></a>
                <p class="copyright"> Gally © 2022</p>
              </div>
          </div>
      </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon px-3 py-3 mb-3">
  <div class="container-fluid">
    <h1 class="logo"><strong><%= link_to "Gally.", root_path, class:"text-decoration-none" %></strong></h1>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars.githubusercontent.com/u/93728030?v=4" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Créer une annonce", new_artwork_path, class:"dropdown-item" %>
              <%= link_to "Mon dashboard", dashboard_path, class:"dropdown-item" %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="artist-card">
    <div class='p-5'>
      <img class="avatar-artist"src="https://kitt.lewagon.com/placeholder/users/simonde24" />
      <strong><%= @user.username %></strong>
    </div>
    <div>
      <p class="artist-card-description">Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum totam ut ducimus asperiores tempora fuga quos molestias et velit, ipsa nulla doloribus laboriosam tenetur similique facilis fugiat dolor tempore maiores.</p>
    </div>

  <div class="container mt-3">
    <div class = "card-grid-profile">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.1)), url(https://media.istockphoto.com/photos/old-paint-with-rust-picture-id1016032032?b=1&k=20&m=1016032032&s=170667a&w=0&h=Iv6Q7Ntl2qbKkji_XmgAMkUjtWKt4ixV0jMqxrzKnKM=)">
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1496504175726-c7b4523c7e81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fHBlaW50dXJlJTIwYWJzdHJhY3R8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60)">
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGVpbnR1cmUlMjB2ZXJ0ZSUyMGFic3RyYWN0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60)">
      </div>
    </div>
  </div>
</div>